apiVersion: apps/v1
kind: Deployment
metadata:
  name: lolbyte
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lolbyte
  template:
    metadata:
      labels:
        app: lolbyte
    spec:
      containers:
        - name: app
          image: registry.digitalocean.com/lolbyte/lolbyte-service:1.0.4
          ports:
            - containerPort: 8080
          imagePullPolicy: Always
          readinessProbe:
            httpGet:
              scheme: HTTP
              path: /health
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: lolbyte
spec:
  selector:
    app: lolbyte
  ports:
    - port: 80
      targetPort: 8080
  type: LoadBalancer